# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-16 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_remove_goodscategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.GoodsCategory', verbose_name='父类目级别'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category',
            field=models.IntegerField(choices=[(1, '一级类'), (2, '二级类'), (3, '三级类')], max_length=32, null=True, verbose_name='商品类录级别'),
        ),
    ]
