# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-18 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0009_auto_20181016_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='昵称')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('time', models.DateTimeField(auto_now=True, max_length=32)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category',
            field=models.IntegerField(choices=[(1, '一级类'), (2, '二级类'), (3, '三级类')], null=True, verbose_name='商品类录级别'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='my_site.GoodsCategory', verbose_name='父类目'),
        ),
    ]
