# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0011_remove_comments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(max_length=32, null=True),
        ),
    ]
